### ISSUE TITLE
【解決済】冗長なタグを削除する仕組みについて

### ISSUE THREAD

**Issue by mizucoffee** [WriterLighter/NML-JavaScript#19]
# `<div></div>`みたいな無駄なタグをどうするか

全部削除してもいいのかな？
正規表現で<_.><\/_.>で削除してもいいんだけど、これだと支障が出る部分があったら教えてください。

水平線とかは`<hr class="number"/>`って形式だから大丈夫だと思う。

**Comment by ygkn** [comment]
`<div class="format-paragraph"></div>`
を削除、じゃだめかな

**Comment by mizucoffee** [comment]
やっぱそっちだけでいいかな？
無駄な<p></p>とかが生成（されないように気をつけてるつもりだけど）されたらもう放置でいいか
