### ISSUE TITLE
【解決済】複数行解析について

### ISSUE THREAD

**Issue by mizucoffee** [WriterLighter/NML-JavaScript#20]
現状1行ずつ解析しているため、リスト系の実装をする場合大幅な改修が必要となるのは不可避。
その際、どのようにして解析するか。

例えば、1行目が
`- いつもの`
だとしたら、リストのフラグを立てて次行もリストだったら〜という仕組み。
かなりまどろっこしいけど一番カンタン。
ただこれ以上拡張するとなると（処理ではなくソース的に）重くなる可能性がある

**Comment by ygkn** [comment]
うん。それでいいと思う。

**Comment by mizucoffee** [comment]
了解ですー。ネスト問題の構想が浮かんだら実装します。
